event_log_track.settings:
  type: config_object
  label: 'Events Log Track settings'
  mapping:
    enable_log_deletion:
      type: boolean
      label: 'Enable log deletion'
    timespan_limit:
      type: integer
      label: 'Timespan Limit'
    batch_size:
      type: integer
      label: 'Batch Size'
    disable_db_logs:
      type: boolean
      label: 'Disable Logging to DB'
    log_cli:
      type: boolean
      label: 'Log to CLI'
    syslog:
      type: mapping
      mapping:
        format:
          type: string
          label: 'Format'
        output_type:
          type: string
          label: 'Output Type'
    stdout:
      type: mapping
      mapping:
        format:
          type: string
          label: 'Format'
        output_type:
          type: string
          label: 'Output Type'