<?php

/**
 * @file
 * Logs menu CUD commands in the event_log_track module.
 */

/**
 * Implements hook_event_log_track_handlers().
 */
function event_log_track_taxonomy_event_log_track_handlers(): array {
  // Taxonomy event log handler.
  $handlers = [];
  $handlers['taxonomy'] = [
    'title' => t('Taxonomy'),
    'operations' => [
      'vocabulary insert',
      'vocabulary update',
      'vocabulary delete',
      'term insert',
      'term update',
      'term delete',
    ],
  ];
  return $handlers;
}

/**
 * Implements hook_taxonomy_vocabulary_insert().
 */
function event_log_track_taxonomy_taxonomy_vocabulary_insert($vocabulary): void {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'vocabulary insert',
    'description' => t('%title (%name)', [
      '%title' => $vocabulary->get('name'),
      '%name' => $vocabulary->get('vid'),
    ]),
    'ref_char' => $vocabulary->get('vid'),
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_taxonomy_vocabulary_update().
 */
function event_log_track_taxonomy_taxonomy_vocabulary_update($vocabulary): void {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'vocabulary update',
    'description' => t('%title (%name)', [
      '%title' => $vocabulary->label(),
      '%name' => $vocabulary->getOriginalId(),
    ]),
    'ref_char' => $vocabulary->getOriginalId(),
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_taxonomy_vocabulary_delete().
 */
function event_log_track_taxonomy_taxonomy_vocabulary_delete($vocabulary): void {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'vocabulary delete',
    'description' => t('%title (%name)', [
      '%title' => $vocabulary->label(),
      '%name' => $vocabulary->getOriginalId(),
    ]),
    'ref_char' => $vocabulary->getOriginalId(),
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function event_log_track_taxonomy_taxonomy_term_insert($term): void {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'term insert',
    'description' => t('%name (%tid)', [
      '%name' => $term->getName(),
      '%tid' => $term->id(),
    ]),
    'ref_numeric' => $term->id(),
    'ref_char' => $term->get('vid')->target_id,
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_taxonomy_term_update().
 */
function event_log_track_taxonomy_taxonomy_term_update($term): void {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'term update',
    'description' => t('%name (%tid)', [
      '%name' => $term->getName(),
      '%tid' => $term->id(),
    ]),
    'ref_numeric' => $term->id(),
    'ref_char' => $term->get('vid')->target_id,
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function event_log_track_taxonomy_taxonomy_term_delete($term): void {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'term delete',
    'description' => t('%name (%tid)', [
      '%name' => $term->getName(),
      '%tid' => $term->id(),
    ]),
    'ref_numeric' => $term->id(),
    'ref_char' => $term->get('vid')->target_id,
  ];
  event_log_track_insert($log);
}
